version: "3.8"

services:
  frank:
    build: .
    environment:
      TZ: Europe/Amsterdam
      dtap.stage: LOC
    volumes:
      - h2-data:/opt/frank/h2
      - logs:/usr/local/tomcat/logs
    ports:
      - "8080:8080"
    restart: unless-stopped

  frank-flow:
    image: frankframework/frank-flow:latest
    environment:
      configurations.directory: /opt/frank/configurations
    volumes:
      - ./src/main/:/opt/frank/:rw
    ports:
      - "8090:8090"

volumes:
  logs:
  h2-data:
