version: "3.8"

services:
  frank:
    build: .
    environment:
      TZ: Europe/Amsterdam
      dtap.stage: LOC
    volumes:
      - logs:/usr/local/tomcat/logs
    ports:
      - "8080:8080"
    depends_on:
      - db

  frank-flow:
    image: frankframework/frank-flow:latest
    environment:
      configurations.directory: /opt/frank/configurations
    volumes:
      - ./src/main/:/opt/frank/:rw
    ports:
      - "8090:8090"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: notificaties
      POSTGRES_USER: frank
      POSTGRES_PASSWORD: frank
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  logs:
  pgdata:
