#
# In this file, all information is stored that are specific for this instance of the Frank!Framework.
#

instance.name=NotificatieComponent
configurations.names.application=${configurations.names}

jdbc.migrator.active=true

# Autorisaties Component (AC)
# Base URL of the autorisaties API from Open Zaak.
nc.zgw.autorisaties-api.root-url=http://openzaak:8001/autorisaties/api/v1

# Auth alias for the NC's own JWT - must match credentials.properties.
nc.zgw.autorisaties-api.auth-alias=autorisaties-api.jwt